config/routes.rb
Rails.application.routes.draw do
  post 'desired_planets/create', to: 'desired_planets#create', as: 'desired_planets_create'
  post 'desired_planets/destroy', to: 'desired_planets#destroy'
  get 'sessions/new'
  post 'sessions/create', to: 'sessions#create'
  post 'sessions/destroy', to: 'sessions#destroy'
  root 'planets#index', as: 'home'
  get 'planets/new'
  post 'planets/create', to: 'planets#create'
  post 'planets/destroyy', to: 'planets#destroyy'
  get 'users/new'
  get 'users/secret'
  post 'users/create', to: 'users#create'
  get 'users/profile_page'
  get 'planets/:id', to: 'planets#show', as: 'planet_show'
  resources :sessions
  resources :planets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/desired_planet.rb
class DesiredPlanet < ApplicationRecord
	belongs_to :user
	belongs_to :planet
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_one_attached :picture

  validates *%i[planet_name picture nearest_star_name distance_in_ly free_space], presence: true
  validates :planet_name, uniqueness: true
  validates :distance_in_ly, numericality: { greater_than_or_equal_to: 0 }
  validates :free_space, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :contact_name, presence: true, format: {
    with: /\A(\p{Cyrillic}+ ?)+\z/,
    message: 'имеет недопустимый формат'
  }
  validates :email, presence: true, uniqueness: true, format: { 
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i,
    message: 'имеет недопустимый формат'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/desired_planets_controller.rb
class DesiredPlanetsController < ApplicationController
  def create
    want_to_visit = DesiredPlanet.new(user_id: params[:user_id], planet_id: params[:planet_id])
    want_to_visit.save
    redirect_to '/planets/%d' % params[:planet_id]
  end

  def destroy
    dont_want_to_visit = DesiredPlanet.find_by(user_id: params[:user_id], planet_id: params[:planet_id])
    dont_want_to_visit.destroy
    redirect_to '/planets/%d' % params[:planet_id]
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  include PlanetsHelper
  before_action :check_admin, only: %i[new create]

  def index
  end

  def new
  end

  def show
    @planet = Planet.find(params[:id])
    @want_to_visit_count = DesiredPlanet.where(planet_id: params[:id]).count
  end

  def create
    @planet = Planet.new(planet_params)
    unless @planet.valid?
      flash[:warning] = @planet.errors.full_messages.to_sentence
      redirect_to '/planets/new'
      return
    else
      @planet.save
      flash[:success] = 'Планета успешно добавлена.'
      redirect_to '/planets/new'
    end
  end

  def destroyy
    planet_to_destroy = Planet.find(params[:planet_id])
    desired_planet_to_destroy = DesiredPlanet.where(planet_id: params[:planet_id])
    desired_planet_to_destroy.destroy_all
    planet_to_destroy.destroy
    flash[:success] = 'Планета успешно удалена.'
    redirect_to home_path
  end

  private

  def planet_params
    params.permit(*%i[planet_name nearest_star_name distance_in_ly description picture free_space])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    unless user
      flash[:warning] = 'Неверный адрес эл. почты или пароль.'
      redirect_to '/sessions/new'
      return
    end
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Добро пожаловать, #{user.contact_name}!"
      redirect_to home_path
    else
      flash[:warning] = 'Неверный адрес эл. почты или пароль.'
      redirect_to '/sessions/new'
    end
  end

  def destroy
    reset_session
    flash[:success] = 'Выход успешно завершен.'
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      flash[:success] = "Добро пожаловать, #{@user.contact_name}!"
      redirect_to home_path
    else 
      flash[:warning] = @user.errors.full_messages.to_sentence
      redirect_to '/users/new'
    end
  end

  def destroy
  end

  def profile_page
    @user = User.find(session[:user_id])
  end

  def secret
  end

  private

  def user_params
    params.permit(:email, :contact_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desired_planets_helper.rb
module DesiredPlanetsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
	def check_admin
		unless session[:user_id]
			flash[:warning] = 'У Вас нет прав на посещение этой страницы.'
			redirect_to home_path
			return
		end
		unless User.find(session[:user_id]).superuser
			flash[:warning] = 'У Вас нет прав на посещение этой страницы.'
			redirect_to home_path
			return
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/desired_planets/create.html.erb
<h1>DesiredPlanets#create</h1>
<p>Find me in app/views/desired_planets/create.html.erb</p>

app/views/desired_planets/destroy.html.erb
<h1>DesiredPlanets#destroy</h1>
<p>Find me in app/views/desired_planets/destroy.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to 'InterstellarVision', home_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if session[:user_id] %>
          <% if User.find(session[:user_id]).superuser %>
            <li>
              <%= link_to 'Добавить планету', '/planets/new', class: 'nav-link active' %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% unless session[:user_id] %>
          <li>
            <%= link_to 'Войти', '/sessions/new', class: 'nav-link active' %>
          </li>
          <li class="nav-link active">|</li>
          <li>
            <%= link_to 'Зарегистрироваться', '/users/new', class: 'nav-link active' %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Профиль', '/users/profile_page', class: 'nav-link active' %>
          </li>
          <li class="nav-link active">|</li>
          <li>
            <%= link_to 'Выйти', '/sessions/destroy', data: {turbo_method: :delete}, class: 'nav-link active' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreditWork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "custom-style" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <br/>

    <div class="container">
      <% unless flash.empty? %>
        <% flash.each do |type, msg| %>
          <% if type == 'warning' %>
            <div class="alert alert-danger">
              <%= msg %>
            </div>
          <% elsif type == 'success' %>
            <div class="alert alert-success">
              <%= msg %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"/>
    </script>
  </body>
</html>

app/views/planets/create.html.erb
<h1>Planets#create</h1>
<p>Find me in app/views/planets/create.html.erb</p>

app/views/planets/destroyy.html.erb
<h1>Planets#destroy</h1>
<p>Find me in app/views/planets/destroy.html.erb</p>

app/views/planets/index.html.erb
<h2 align="center">Планеты</h2>
<br/>

<% planets = Planet.all %>

<% planets.each_slice(3) do |elems| %>
	<div class="row1">
		<% elems.each do |planet| %>
			<div class="col1">
				<div class="card" style="width: 18rem; height: 475px;">
					<%= image_tag planet.picture, class: 'card-img-top' %>
					<div class="card-body">
						<h5 class="card-title"><%= planet.planet_name %></h5>
						<p class="card-text"><%= planet.description %></p>
						<%= button_to 'Подробнее', planet_show_path(planet.id), method: :get, class: 'btn btn-outline-dark' %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
	<br/>
<% end %>

app/views/planets/new.html.erb
<h2>Добавить планету</h2>
<br/>

<%= form_with url: '/planets/create', method: :post do |form| %>
	<p>
		<%= form.label 'Имя планеты', class: 'form-label' %>
		<%= form.text_field :planet_name, class: 'form-control' %>
	</p>
	<p>
		<%= form.label 'Фотография', class: 'form-label' %>
		<%= form.file_field :picture, class: 'form-control' %>
	</p>
	<p>
		<%= form.label 'Имя ближайшей звезды', class: 'form-label' %>
		<%= form.text_field :nearest_star_name, class: 'form-control' %>
	</p>
	<p>
		<%= form.label 'Расстояние в световых годах', class: 'form-label' %>
		<%= form.number_field :distance_in_ly, class: 'form-control' %>
	</p>
	<p>
		<%= form.label 'Описание', class: 'form-label' %>
		<%= form.text_field :description, class: 'form-control' %>
	</p>
	<p>
		<%= form.label 'Количество мест на посещение', class: 'form-label' %>
		<%= form.number_field :free_space, class: 'form-control' %>
	</p>
	<p>
		<%= form.submit 'Добавить планету', class: 'btn btn-outline-dark' %>
	</p>
<% end %>

app/views/planets/show.html.erb
<h2 align="center"><%= @planet.planet_name %></h2>
<br/>

<p>
	<%= image_tag 'rocket_icon.svg', width: "18rem" %>
	Имя ближайшей звезды: <%= @planet.nearest_star_name %>
</p>
<p>
	<%= image_tag 'rocket_icon.svg', width: "18rem" %>
	Расстояние от Земли: <%= @planet.distance_in_ly %> 
	<% if (@planet.distance_in_ly % 10) == 1 %>
		световой год
	<% elsif (@planet.distance_in_ly % 10).between?(2, 4) %>
		световых года
	<% else %>
		световых лет
	<% end %>
</p>
<p>
	<%= image_tag 'rocket_icon.svg', width: "18rem" %>
	Описание: <%= @planet.description %>
</p>
<p>
	<%= image_tag @planet.picture, width: '350rem', class: 'rounded' %>
</p>
<br/><br/><br/>
<% if session[:user_id] %>

	<div class="custom-row">
		<div class="cutsom-col">
			<% already_want_to_visit = DesiredPlanet.find_by(user_id: session[:user_id], planet_id: @planet.id) %>
			<% unless already_want_to_visit %>
				<% unless @planet.free_space - @want_to_visit_count == 0 %>
					<%= button_to 'Хочу посетить!', {:controller => 'desired_planets', :action => 'create', :user_id => session[:user_id], :planet_id => @planet.id}, class: 'btn btn-outline-dark' %>
				<% else %>
					<button class="btn btn-outline-dark" disabled>Записаться невозможно.</button>
				<% end %>
			<% else %>
				<%= button_to 'Не хочу посещать.', {:controller => 'desired_planets', :action => 'destroy', :user_id => session[:user_id], :planet_id => @planet.id}, class: 'btn btn-outline-dark' %>
			<% end %>
		</div>
		<% if User.find(session[:user_id]).superuser %>
		<div class="custom-col">
			<%= button_to 'Удалить планету', {:controller => 'planets', :action => 'destroyy', :user_id => session[:user_id], :planet_id => @planet.id}, class: 'btn btn-outline-dark' %>
		</div>
		<% end %>
	</div>
<% else %>
	<p>
		Чтобы отметиться, что Вы хотите посетить эту планету, вам необходимо войти в аккаунт.
	</p>
<% end %>
<br/>
<p>
	Свободных мест: <%= @planet.free_space - @want_to_visit_count %>
</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h2 align="center">Регистрация</h2>
<br/>

<%= form_with url: '/users/create', method: :post do |form| %>
	<p>
		<%= form.label 'Адрес эл. почты', class: 'form-label' %>
		<%= form.email_field :email, class: 'form-control' %>
	</p>
	<p>
		<%= form.label 'Полное имя', class: 'form-label' %>
		<%= form.text_field :contact_name, class: 'form-control' %>
	</p>
	<p>
		<%= form.label 'Пароль', class: 'form-label' %>
		<%= form.password_field :password, class: 'form-control' %>
	</p>
	<p>
		<%= form.label 'Подтверждение пароля', class: 'form-label' %>
		<%= form.password_field :password_confirmation, class: 'form-control' %>
	</p>
	<p>
		<%= form.submit 'Зарегистрироваться', class: 'btn btn-outline-dark' %>
	</p>
<% end %>

app/views/users/profile_page.html.erb
<h2 align="center">Здравствуйте, <%= @user.contact_name %>!</h2>
<br/>
<% wanted_planets = DesiredPlanet.where(user_id: session[:user_id]).pluck(:planet_id) %>
<% if wanted_planets.length != 0 %>
<p>
	Планеты, которые Вы хотите посетить:
	<% wanted_planets.each do |wanted_planet| %>
		<p>
			<%= image_tag 'planet_icon.svg', width: '18rem' %>&nbsp;
			<%= link_to Planet.find(wanted_planet).planet_name, '/planets/%d' % wanted_planet, style: 'color: black;' %>
		</p>
	<% end %>
</p>
<% else %>
<p>
	Вы не хотите посетить никакие планеты.
</p>
<% end %>

app/views/users/secret.html.erb
<h2 align="center">Секретная страница))</h2>
<canvas id="canvas" width="300" height="300"></canvas>
<script>
	const sun = new Image();
	const moon = new Image();
	const earth = new Image();
	function init() {
	  sun.src = '<%= asset_path 'canvas_sun.png' %>';
	  moon.src = '<%= asset_path 'canvas_moon.png' %>';
	  earth.src = '<%= asset_path 'canvas_earth.png' %>';
	  window.requestAnimationFrame(draw);
	}

	function draw() {
	  const ctx = document.getElementById("canvas").getContext("2d");

	  ctx.globalCompositeOperation = "destination-over";
	  ctx.clearRect(0, 0, 500, 500); // clear canvas

	  ctx.fillStyle = "rgba(0, 0, 0, 0.4)";
	  ctx.strokeStyle = "rgba(0, 153, 255, 0.4)";
	  ctx.save();
	  ctx.translate(150, 150);

	  // Earth
	  const time = new Date();
	  ctx.rotate(
	    ((2 * Math.PI) / 60) * time.getSeconds() +
	      ((2 * Math.PI) / 60000) * time.getMilliseconds()
	  );
	  ctx.translate(105, 0);
	  ctx.drawImage(earth, -27, -27, 50, 50);

	  // Moon
	  ctx.save();
	  ctx.rotate(
	    ((2 * Math.PI) / 6) * time.getSeconds() +
	      ((2 * Math.PI) / 6000) * time.getMilliseconds()
	  );
	  ctx.translate(0, 28.5);
	  ctx.drawImage(moon, -3.5, -3.5, 20, 20);
	  ctx.restore();

	  ctx.restore();

	  ctx.beginPath();
	  ctx.arc(150, 150, 105, 0, Math.PI * 2, false); // Earth orbit
	  ctx.stroke();

	  ctx.drawImage(sun, 50, 50, 200, 200);

	  window.requestAnimationFrame(draw);
	}

	init();
</script>